global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'ai-services'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'bentoml:8000' # FastAPI + BentoML 서비스
        - 'grafana:3000' 

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  - job_name: 'nvidia-gpu'
    static_configs:
      - targets: ['localhost:9835']
    scrape_interval: 5s

  - job_name: 'windows-exporter'
    static_configs:
      - targets: ['localhost:9182']
