stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - src/prepare_data.py
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train_model:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed_data.csv
    params:
      - train.learning_rate
      - train.batch_size
    outs:
      - models/model.pth
    metrics:
      - metrics/train_metrics.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pth
      - data/test_data.csv
    metrics:
      - metrics/eval_metrics.json