[project]
name = "ai-document-archive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "geopy>=2.4.1",
    "konlpy>=0.6.0",
    "opencv-python-headless>=4.12.0.88",
    "piexif>=1.1.3",
    "setuptools>=80.9.0",
]
